### ISSUE TITLE
Feature : Implement de-authentication attack

### ISSUE THREAD

**Issue by abhisharma404** [abhisharma404/vault#62]
Implement a de-authentication attack, use Scapy to implement this.

The following features needs to be taken care of:
1. User can pass the interface name
2. If the interface name is valid then use `airmon-ng` to monitor & collect all the nearby available WiFi networks.
3. Start sending de-auth packets to the selected network.

**Comment by mzfr** [comment]
@abhisharma404 Any reason to close this?

**Comment by abhisharma404** [comment]
@mzfr It's implemented. Did not reference it.
