### ISSUE TITLE
I have problems trying to scan any URL.

### ISSUE THREAD

**Issue by Juanito1** [abhisharma404/vault#93]
**Describe the bug**
I try to beging a scan and it says: Please Check log file for information about any errors.

**Screenshots**

![Screenshot_2019-05-31-20-42-43-304_com thecrackertechnology andrax](https://user-images.githubusercontent.com/29584342/58741975-c35e5700-83e5-11e9-91c0-fb9027608a8f.png)

**Desktop**
 - OS: Andrax
 - Browser Chrome
 - Version 2.0

**Smartphone (please complete the following information):**
 - Device: Xiaomi redmi Note 6 Pro
 - OS: MIUI 10.3.3
 - Browser Chrome
 - Version 10.3.3

**Additional context**

**Comment by mzfr** [comment]
Going to your URL it redirects to http://prepa8.unam.mx/p8/ so maybe try to use this URL.
Also, check the log files for what went wrong.

**Comment by Juanito1** [comment]
I try it again and not work, and the log file doesnt write anything.

**Comment by mzfr** [comment]
@Juanito1 	The way you are using it is wrong. You have to provide other arguments along with the URL.

Try `vault -u prep8.uname.mx -info` to get general information. And in the same way you can use other features too.

**Comment by Juanito1** [comment]
Thank you very much, you already solved my doubt.
